CREATE TABLE EQUIPE(
  NOME_EQUIPE VARCHAR(50) NOT NULL,
  PAIS_SEDE VARCHAR(36) NOT NULL,
  DATA_FUNDACAO VARCHAR(20) NOT NULL,
  ID_EQUIPE VARCHAR(15) PRIMARY KEY NOT NULL  
);


CREATE TABLE PATROCINADOR(
  ID_PATROCINADOR VARCHAR(15) PRIMARY KEY NOT NULL,
  NOME_PATROCINADOR VARCHAR(25) NOT NULL,
  TIPO_PATROCINADOR VARCHAR(15) NOT NULL
);

CREATE TABLE FABRICANTE(
  ID_FABRICANTE VARCHAR(15) PRIMARY KEY NOT NULL,
  CUSTO_TEMPORADA INT,
  EQUIPES_ASSOCIADAS VARCHAR(15) NOT NULL,
  NOME_FABRICANTE VARCHAR(25) NOT NULL
);

CREATE TABLE FUNCIONARIO(
  ID_FUNCIONÁRIO VARCHAR(15) PRIMARY KEY NOT NULL,
  SALARIO INT,
  EMAIL VARCHAR(20) NOT NULL,
  ENDEREÇO VARCHAR(30) NOT NULL,
  DATE_NASCIMENTO VARCHAR(8) NOT NULL, 
  NOME_FUNCIONARIO VARCHAR(30) NOT NULL,
  TELEFONE VARCHAR(13) NOT NULL 
);

CREATE TABLE MECANICO(
  ID_FUNCIONARIO VARCHAR(15) PRIMARY KEY REFERENCES FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE,
  ID_CREA VARCHAR(15) PRIMARY KEY NOT NULL,
  NIVEL_TREINAMENTO VARCHAR(10) NOT NULL
);

CREATE TABLE CHEFE_EQUIPE(
  ID_FUNCIONARIO VARCHAR(15) PRIMARY KEY REFERENCES FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE,
  EXPERIENCIA_ANOS INT,
  FORMACAO VARCHAR(20)
);

CREATE TABLE DEPART_MEDICO(
  ID_FUNCIONARIO VARCHAR(15) PRIMARY KEY REFERENCES FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE,
  CERTIFICACAO VARCHAR(15) NOT NULL,
  ESPECIALIDADE_MEDICA VARCHAR(15) NOT NULL
);

CREATE TABLE PILOTO(
  ID_FUNCIONARIO VARCHAR(15) PRIMARY KEY REFERENCES FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE,
  TIPO VARCHAR(10) NOT NULL,
  PONTOS INT
);

CREATE TABLE CARRO(
  ID_CARRO VARCHAR(15) PRIMARY KEY NOT NULL,
  CHASSI VARCHAR(15) NOT NULL,
  COR VARCHAR(10) NOT NULL
);

CREATE TABLE PECA(
  ID_PECA VARCHAR(10) PRIMARY KEY NOT NULL,
  NOME_PECA VARCHAR(30) NOT NULL
);

CREATE TABLE CORRIDA(
  ID_CORRIDA VARCHAR (15) PRIMARY KEY NOT NULL,
  TEMPORADA INT,
  ANO INT,
  LOCALIZACAO VARCHAR(30) NOT NULL
);
